version: "3.7"

services:
    database:
        image: mysql:5.7
        container_name: database
        environment:
            MYSQL_ROOT_PASSWORD: thomas1234
            MYSQL_DATABASE: bookstore_db
            MYSQL_USER: alperenmsahin
            MYSQL_PASSWORD: thomas1234
        networks:
            - mynet    

    myapp:
        image: bookstore-api:latest
        container_name: myapp
        restart: always
        depends_on:
            - database
        networks:
            - mynet
networks:
    mynet:    
            

